
# Supabase configuration file
project_id = "rhjucbgwipmmiisskmcz"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://preview--mimic-and-mirror-app.lovable.app"
additional_redirect_urls = ["https://preview--mimic-and-mirror-app.lovable.app/login", "https://preview--mimic-and-mirror-app.lovable.app/reset-password"]
