// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctsjvuoucopnederhkko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0c2p2dW91Y29wbmVkZXJoa2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzIwOTYsImV4cCI6MjA2MDE0ODA5Nn0.p0ZVoRmt_7niZf5HfO6ndRL31ytzpL598f5AN_Xq670";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);